### ISSUE TITLE
include bios.h is not working

### ISSUE THREAD

**Issue by WhitehawkTailor** [badlogic/vscode-dos-dev-extension#2]
In the first Demo project the #include <bios.h> line is marked with red. That is why other parts of the source also are marked with red to indicate errors.

On the other hand the build process terminates with zero code.

But the program does not run and waits for the debugger in the DOSBox screen.
Waiting for debugger...

In the console of VS there are a couple of warnings:
LOG: MT32: failed to locate ROMs.
LOG: WARNING: No translation support (to host) for code page 0
LOG:        481 ERROR BIOS:Keyboard layout file auto not found
LOG:        481 ERROR BIOS:Keyboard layout file auto not found

**Comment by badlogic** [comment]
Sorry for that. I'll need more info. 

* What operating system are you working on?
* The debugger (`<your-home-directory>/.dos/gdb/gdb`) connects to the program in DOSBox via TCP on port 5123. Please make your firewall let's the two apps communicate with each other, and that no other app on your system is using port 5123.
* Please post the full log from DOSBox-x
* Regarding the bios.h error, does the `build/` folder contain a file called `compile_commands.json`? If so, open the command palette (CTRL+SHIFT+P), type `clangd restart` and press enter. If not, then open the command palette and type `cmake build` plus enter, then open the command palette again and type `clangd restart` plus enter.

**Comment by WhitehawkTailor** [comment]
I use ubuntu 22.04.1 LTS.
The situation has changed. Maybe the restart caused some changes.
I already have this kind of experience with VSCode couple of times.
Right now the bios include is not highlighted.
For a while the debug did not started. I don't know what I did change, but it works fine now.

thanks for the quick response.
This is a great job.
Thanks for the experience to be able to do DOS programing again :)

**Comment by badlogic** [comment]
Glad it worked!
